name: RAVE-iEEG Synchronize Forks

on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 0 * * *' # Sync every day at midnight

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'rave-ieeg'
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      UPSTREAM_REPO: dipterix/rave-gists
    steps:
      - name: Checkout upstream
        uses: actions/checkout@v3
        with:
          repository: ${{ env.UPSTREAM_REPO }}
          fetch-depth: 2
      - name: Sync changes
        run: |
          git push origin HEAD:sync
