name: RAVE-iEEG Synchronize Forks

on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 0 * * *' # Sync every day at midnight

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'rave-ieeg'
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      UPSTREAM_OWNER: dipterix
      UPSTREAM_REPO: rave-gists
    steps:
      - name: Checkout upstream
        uses: actions/checkout@v3
      - name: Sync changes
        run: |
          git remote add upstream https://github.com/${{ env.UPSTREAM_OWNER }}/${{ env.UPSTREAM_REPO }}.git
          git fetch upstream
          git checkout ${{ github.ref_name }}
          git rebase upstream/${{ github.ref_name }}
          git push -f origin ${{ github.ref_name }}
